<a href="https://colab.research.google.com/github/arkapriyathecoderinprogress/DataScience2.0/blob/main/Movies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import requests
response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=bda5a973510a630638fee6591ab1044d&language=en-US&page=1')
temp_df=pd.DataFrame(response.json()['results'][['id','title','overview','release_date','popularity','vote_average','vote_count']])

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,135.298,8.703,26057
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,149.410,8.695,19752
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,131.373,8.577,11933
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,89.065,8.568,15335
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,66.964,8.542,8207
5,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,110.761,8.538,15853
6,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,37.511,8.536,4376
7,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,142.690,8.515,31835
8,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,96.508,8.511,17465
9,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,103.764,8.506,16759
10,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,100.206,8.496,10937
11,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,365.914,8.489,26995
12,122,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,2003-12-01,132.597,8.479,23314
13,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,206.801,8.475,26530
14,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-22,77.262,8.468,8229
15,769,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",1990-09-12,239.698,8.466,12341
16,12477,Grave of the Fireflies,"In the final months of World War II, 14-year-o...",1988-04-16,0.600,8.464,5219
17,11216,Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",1988-11-17,61.391,8.454,4180
18,346,Seven Samurai,A samurai answers a village's request for prot...,1954-04-26,39.433,8.453,3474
19,637,Life Is Beautiful,A touching story of an Italian book seller of ...,1997-12-20,58.315,8.451,12686

In [10]:
df=pd.DataFrame()

In [11]:
df

Empty DataFrame
Columns: []
Index: []

In [21]:
for i in range(1,468):
  response=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=bda5a973510a630638fee6591ab1044d&language=en-US&page={}'.format(i))
  temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
  df=pd.concat([df,temp_df],ignore_index=True)
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,135.298,8.703,26057
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,149.410,8.695,19752
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,131.373,8.577,11933
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,89.065,8.568,15335
4,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,66.964,8.542,8207
...,...,...,...,...,...,...,...
18655,12142,Alone in the Dark,Edward Carnby is a private investigator specia...,2005-01-28,22.275,3.229,574
18656,13805,Disaster Movie,"The filmmaking team behind the hits ""Scary Mov...",2008-08-29,35.105,3.203,989
18657,11059,House of the Dead,"Set on an island off the coast, a techno rave ...",2003-04-11,18.327,3.125,369
18658,14164,Dragonball Evolution,"On his 18th birthday, Goku receives a mystical...",2009-03-12,28.301,2.890,1980
18659,40016,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,2010-02-27,8.893,2.208,320

In [22]:
df.shape

(18660, 7)

In [23]:
df.to_csv('movies.csv')